### ISSUE TITLE
Set up semantic release

### ISSUE THREAD

**Issue by haydn** [colonydb/anthill#10]
```
name: Publish Package to NPM

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: "Build"
        run: pnpm turbo build
        working-directory: ./packages/anthill
      - name: "Release"
        run: pnpm semantic-release
        working-directory: ./packages/anthill
```
